---
title: "Datasaurus"
output: html_notebook
---

```{r packages, warning = FALSE, message = FALSE}
library(tidyverse)
library(datasauRus)
```

# Exploratory Analysis

```{r numerical summaries}
datasaurus_dozen %>% 
  group_by(dataset) %>% 
  summarise(mean_x = mean(x),
            var_x  = var(x),
            mean_y = mean(y),
            var_y  = var(y),
            cor_xy = cor(x,y))
```

# X density

```{r plot, fig.height=10}
datasaurus_dozen %>% 
  ggplot(mapping = aes(x = x)) +
  geom_density() +
  facet_wrap(~dataset, ncol = 3)
```

# Y density
                          
```{r plot, fig.height=10}
datasaurus_dozen %>% 
  ggplot(mapping = aes(x = y)) +
  geom_density() +
  facet_wrap(~dataset, ncol = 3)
```

# Plot

```{r plot, fig.height=10}
datasaurus_dozen %>% 
  ggplot(mapping = aes(x = x, y = y)) +
  geom_point() +
  facet_wrap(~dataset, ncol = 3)
```


# References

Description of the `datasauRus` package on
[CRAN](https://cran.r-project.org/web/packages/datasauRus/vignettes/Datasaurus.html).